import fs from 'node:fs/promises';
import path from 'node:path';
import { pathExists, readJson, readText, slug } from '../graph-utils.mjs';

const sourceExtensions = new Set([
  '.ts',
  '.tsx',
  '.js',
  '.jsx',
  '.mjs',
  '.cjs',
  '.vue',
  '.svelte',
  '.html',
  '.java',
  '.kt',
  '.kts',
  '.cs'
]);

const ignoredDirs = new Set([
  '.git',
  '.next',
  '.nuxt',
  '.svelte-kit',
  'build',
  'coverage',
  'dist',
  'node_modules',
  'out',
  'playwright-report',
  'target',
  'test-results'
]);

const stateKeywords = [
  'loaded',
  'loading',
  'empty',
  'error',
  'validation-error',
  'permission-denied',
  'unauthorized',
  'forbidden',
  'success',
  'disabled',
  'read-only'
];

export async function buildManifest(options = {}) {
  const appRoot = options.appRoot ?? process.env.SOURCE_APP_ROOT ?? '.';
  const appUrl = options.appUrl ?? process.env.SOURCE_APP_URL ?? process.env.APP_BASE_URL ?? 'http://localhost:3000';
  const root = path.resolve(process.cwd(), appRoot);
  const packageJson = await readPackageJson(root);
  const appName = options.appName ?? process.env.SOURCE_APP_NAME ?? packageJson?.name ?? path.basename(root);
  const files = await listSourceFiles(root);
  const scanOptions = {
    nextProject: await isNextProject(root, packageJson, files)
  };
  const sourceFiles = [];
  const routes = new Map();
  const apiDependencies = [];
  const frameworks = new Set();

  for (const file of files) {
    const relativeFile = path.relative(process.cwd(), file);
    const text = await fs.readFile(file, 'utf8');
    sourceFiles.push({ file, relativeFile, text });
    detectFrameworks(file, text, frameworks, scanOptions);
  }

  const components = collectComponentSnippets(sourceFiles);

  for (const { file, relativeFile, text } of sourceFiles) {
    for (const nextRoute of discoverRoutes(file, root, text, scanOptions)) {
      mergeRoute(routes, enrichRoute(nextRoute, relativeFile, text, components));
    }

    for (const dependency of discoverApiDependencies(file, root, text)) {
      apiDependencies.push(dependency);
    }
  }

  const normalizedRoutes = Array.from(routes.values())
    .filter((route) => route.path && !route.path.includes('*'))
    .sort((a, b) => a.path.localeCompare(b.path));

  return {
    name: appName,
    description: 'Generated by the generic source scanner. Review and enrich app-specific auth, role, and state details as needed.',
    capturePrefix: slug(appName),
    defaultUrl: appUrl,
    sourceRoot: path.relative(process.cwd(), root) || '.',
    scanner: {
      adapter: 'generic-source',
      filesScanned: files.length,
      frameworks: Array.from(frameworks).sort(),
      note: 'Heuristic scan across common frontend and backend source patterns. App-specific adapters can improve role/auth precision.'
    },
    users: inferUsers(normalizedRoutes),
    routes: normalizedRoutes,
    apiDependencies: uniqueBy(
      apiDependencies,
      (item) => `${item.method}:${item.path}:${item.source}`
    ).sort((a, b) => a.path.localeCompare(b.path))
  };
}

async function readPackageJson(root) {
  const packagePath = path.join(root, 'package.json');
  if (!(await pathExists(path.relative(process.cwd(), packagePath)))) return null;
  return readJson(path.relative(process.cwd(), packagePath));
}

async function isNextProject(root, packageJson, files) {
  const dependencies = {
    ...(packageJson?.dependencies ?? {}),
    ...(packageJson?.devDependencies ?? {})
  };
  if (dependencies.next) return true;

  const configFiles = ['next.config.js', 'next.config.mjs', 'next.config.ts'];
  for (const configFile of configFiles) {
    if (await pathExists(path.relative(process.cwd(), path.join(root, configFile)))) return true;
  }

  return files.some((file) => /(?:^|\/)(?:src\/)?app\/.+\/page\.(?:t|j)sx?$/.test(file.replaceAll(path.sep, '/')));
}

async function listSourceFiles(root) {
  const files = [];

  async function walk(dir) {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.isDirectory()) {
        if (!ignoredDirs.has(entry.name)) await walk(path.join(dir, entry.name));
        continue;
      }

      const file = path.join(dir, entry.name);
      if (sourceExtensions.has(path.extname(entry.name))) files.push(file);
    }
  }

  await walk(root);
  return files;
}

function detectFrameworks(file, text, frameworks, options) {
  const normalized = file.replaceAll(path.sep, '/');
  if (/from\s+['"]react['"]|<Route\b|createBrowserRouter|react-router/i.test(text) || (/\.(t|j)sx$/i.test(normalized) && /<\w+[\s>]/.test(text))) frameworks.add('react');
  if (options.nextProject && /app\/.+\/page\.(t|j)sx?$|pages\/.+\.(t|j)sx?$/i.test(normalized)) frameworks.add('next');
  if (/@Component\s*\(|RouterModule\.forRoot|:\s*Routes\b/i.test(text)) frameworks.add('angular');
  if (/<template>|defineComponent|createRouter/i.test(text) || normalized.endsWith('.vue')) frameworks.add('vue');
  if (/@Controller|@RestController|@GetMapping|@PostMapping|@RequestMapping/i.test(text)) frameworks.add('spring');
  if (/@page\s+"\/|MapGet\(|MapPost\(|Controller\b/i.test(text) && normalized.endsWith('.cs')) frameworks.add('dotnet');
  if (normalized.endsWith('.html')) frameworks.add('html');
}

function discoverRoutes(file, root, text, options) {
  return [
    ...(options.nextProject ? discoverNextRoutes(file, root) : []),
    ...discoverReactRoutes(text),
    ...discoverAngularRoutes(text),
    ...discoverVueRoutes(text),
    ...discoverHtmlRoutes(text),
    ...discoverSpringRoutes(text),
    ...discoverDotnetRoutes(text)
  ];
}

function discoverNextRoutes(file, root) {
  const normalized = path.relative(root, file).replaceAll(path.sep, '/');
  const match = normalized.match(/^(?:src\/)?app\/(.+)\/page\.(?:t|j)sx?$/);
  const pagesMatch = normalized.match(/^(?:src\/)?pages\/(.+)\.(?:t|j)sx?$/);
  const routeFile = match?.[1] ?? pagesMatch?.[1];
  if (!routeFile) return [];

  const route = routeFile
    .replace(/\/index$/, '')
    .split('/')
    .filter((part) => !part.startsWith('(') && !part.startsWith('@'))
    .map((part) => part.startsWith('[') ? `:${part.slice(1, -1).replace('...', '')}` : part)
    .join('/');
  return [{ path: normalizeRoute(route), sourceKind: 'file-route' }];
}

function discoverReactRoutes(text) {
  return collectMatches(text, [
    /<Route\b[^>]*\bpath=(?:{)?['"`]([^'"`{}]+)['"`]/g,
    /\bpath\s*:\s*['"`]([^'"`]+)['"`]/g,
    /\bto=(?:{)?['"`](\/[^'"`{}]+)['"`]/g
  ], 'react-route');
}

function discoverAngularRoutes(text) {
  return collectMatches(text, [
    /\bpath\s*:\s*['"`]([^'"`]+)['"`]/g,
    /\brouterLink=(?:{)?['"`]([^'"`{}]+)['"`]/g
  ], 'angular-route');
}

function discoverVueRoutes(text) {
  return collectMatches(text, [
    /\bpath\s*:\s*['"`]([^'"`]+)['"`]/g,
    /\bto=(?:{)?['"`](\/[^'"`{}]+)['"`]/g
  ], 'vue-route');
}

function discoverHtmlRoutes(text) {
  return collectMatches(text, [
    /\bhref=['"`](\/[^'"`#?]+)['"`]/g,
    /\bdata-route=['"`](\/[^'"`]+)['"`]/g
  ], 'html-route');
}

function discoverSpringRoutes(text) {
  const classPrefix = firstMatch(text, /@RequestMapping\s*\(\s*(?:value\s*=\s*)?['"`]([^'"`]+)['"`]/);
  return collectMatches(text, [
    /@(Get|Post|Put|Patch|Delete|Request)Mapping\s*\(\s*(?:value\s*=\s*)?['"`]([^'"`]+)['"`]/g
  ], 'spring-route', (match) => ({
    path: match[1] === 'Request' && match[2] === classPrefix ? '' : joinRoutes(classPrefix, match[2]),
    method: match[1].replace('Mapping', '').toUpperCase() || 'REQUEST'
  }));
}

function discoverDotnetRoutes(text) {
  const controllerPrefix = firstMatch(text, /\[Route\(\s*['"`]([^'"`]+)['"`]\s*\)\]/);
  return collectMatches(text, [
    /\[Http(Get|Post|Put|Patch|Delete)(?:\(\s*['"`]([^'"`]*)['"`]\s*\))?\]/g,
    /Map(Get|Post|Put|Patch|Delete)\(\s*['"`]([^'"`]+)['"`]/g
  ], 'dotnet-route', (match) => ({
    path: joinRoutes(controllerPrefix, match[2] ?? ''),
    method: match[1].toUpperCase()
  }));
}

function collectMatches(text, patterns, sourceKind, mapper) {
  const routes = [];
  for (const pattern of patterns) {
    for (const match of text.matchAll(pattern)) {
      const mapped = mapper ? mapper(match) : { path: match[1] };
      if (!mapped.path) continue;
      const routePath = normalizeRoute(mapped.path);
      if (!isLikelyApplicationRoute(routePath)) continue;
      routes.push({
        ...mapped,
        path: routePath,
        sourceKind,
        contextText: enclosingObject(text, match.index ?? 0) ?? nearbyText(text, match.index ?? 0)
      });
    }
  }
  return routes;
}

function discoverApiDependencies(file, root, text) {
  const source = path.relative(process.cwd(), file);
  const dependencies = [];
  const patterns = [
    /\b(?:fetch|axios\.(?:get|post|put|patch|delete))\(\s*['"`]([^'"`]+)['"`]/g,
    /\bhttp\.(?:get|post|put|patch|delete)\(\s*['"`]([^'"`]+)['"`]/g
  ];

  for (const pattern of patterns) {
    for (const match of text.matchAll(pattern)) {
      if (match[1].startsWith('/')) dependencies.push({ path: match[1], method: 'UNKNOWN', source });
    }
  }

  return dependencies;
}

function enrichRoute(route, source, text, components) {
  const routeText = route.contextText ?? text;
  const component = inferComponent(routeText, source);
  const componentText = (components.get(component) ?? []).map((item) => item.text).join('\n');
  const combinedText = `${routeText}\n${componentText}`;
  const sourceFiles = unique([
    source,
    ...(components.get(component) ?? []).map((item) => item.source)
  ]);
  const actions = unique([
    ...extractArrayProperty(combinedText, 'actions'),
    ...extractButtonActions(combinedText),
    ...extractSubmitActions(combinedText),
    ...(route.method ? [`${route.method.toLowerCase()} ${route.path}`] : [])
  ]);
  const fields = unique([
    ...extractArrayProperty(combinedText, 'fields'),
    ...extractAttributes(combinedText, ['aria-label', 'placeholder', 'name']),
    ...extractLabels(combinedText)
  ]);
  const testIds = unique([
    ...extractArrayProperty(combinedText, 'testIds'),
    ...extractTestIds(combinedText)
  ]).filter((testId) => !testId.includes('${'));
  const states = unique([
    ...extractArrayProperty(combinedText, 'states'),
    ...inferStates(combinedText, route.sourceKind)
  ]);
  const roles = unique([
    ...extractArrayProperty(combinedText, 'roles'),
    ...inferRoles(combinedText)
  ]);

  return {
    path: route.path,
    component,
    roles,
    actions,
    fields,
    states,
    testIds,
    sourceFiles,
    sourceKinds: [route.sourceKind],
    apiMethods: route.method ? [route.method] : []
  };
}

function inferComponent(text, source) {
  return firstMatch(text, /export\s+default\s+function\s+([A-Z][A-Za-z0-9_]*)/)
    ?? firstMatch(text, /function\s+([A-Z][A-Za-z0-9_]*)\s*\(/)
    ?? firstMatch(text, /class\s+([A-Z][A-Za-z0-9_]*)/)
    ?? firstMatch(text, /element\s*=\s*{?\s*<([A-Z][A-Za-z0-9_]*)/)
    ?? firstMatch(text, /component\s*:\s*['"`]([A-Z][A-Za-z0-9_]*)['"`]/)
    ?? firstMatch(text, /component\s*:\s*([A-Z][A-Za-z0-9_]*)/)
    ?? firstMatch(text, /name\s*:\s*['"`]([A-Z][A-Za-z0-9_-]*)['"`]/)
    ?? toComponentName(path.basename(source, path.extname(source)));
}

function collectComponentSnippets(sourceFiles) {
  const components = new Map();
  for (const { relativeFile, text } of sourceFiles) {
    const patterns = [
      /export\s+default\s+function\s+([A-Z][A-Za-z0-9_]*)/g,
      /export\s+function\s+([A-Z][A-Za-z0-9_]*)/g,
      /function\s+([A-Z][A-Za-z0-9_]*)\s*\(/g,
      /class\s+([A-Z][A-Za-z0-9_]*)/g,
      /(?:export\s+)?const\s+([A-Z][A-Za-z0-9_]*)\s*=/g
    ];

    for (const pattern of patterns) {
      for (const match of text.matchAll(pattern)) {
        const name = match[1];
        const snippet = nearbyText(text, match.index ?? 0, 8000);
        const existing = components.get(name) ?? [];
        existing.push({ source: relativeFile, text: snippet });
        components.set(name, existing);
      }
    }
  }
  return components;
}

function extractButtonActions(text) {
  const actions = [];
  for (const match of text.matchAll(/<button\b[^>]*>([\s\S]*?)<\/button>/gi)) {
    const label = stripTags(match[1]);
    if (label) actions.push(label);
  }
  for (const match of text.matchAll(/(?:data-testid|data-test|data-cy)=['"`]([^'"`]*(?:button|submit|save|create|delete|edit|export|download|retry|refresh|invite)[^'"`]*)['"`]/gi)) {
    actions.push(match[1].replace(/[-_]/g, ' '));
  }
  return actions;
}

function extractSubmitActions(text) {
  const actions = [];
  for (const match of text.matchAll(/\bon(?:Click|Submit)\s*=\s*{?\s*([A-Za-z0-9_]+)/g)) {
    actions.push(match[1].replace(/^handle/, '').replace(/([a-z])([A-Z])/g, '$1 $2').toLowerCase());
  }
  return actions;
}

function extractAttributes(text, names) {
  return names.flatMap((name) => Array.from(text.matchAll(new RegExp(`\\b${name}=['"\`]([^'"\`]+)['"\`]`, 'gi'))).map((match) => match[1]));
}

function extractLabels(text) {
  return Array.from(text.matchAll(/<label\b[^>]*>([\s\S]*?)<\/label>/gi)).map((match) => stripTags(match[1]));
}

function extractTestIds(text) {
  return Array.from(text.matchAll(/\b(?:data-testid|data-test|data-cy)=['"`]([^'"`]+)['"`]/gi)).map((match) => match[1]);
}

function inferStates(text, sourceKind) {
  const normalized = text.toLowerCase();
  const states = ['loaded'];
  for (const state of stateKeywords) {
    const terms = [state, state.replace('-', ' '), state.replace('-', '')];
    if (terms.some((term) => normalized.includes(term))) states.push(state);
  }
  if (/\brequired\b|Validators\.required|@NotNull|@NotBlank|aria-invalid|role=['"`]alert['"`]/i.test(text)) {
    states.push('validation-error');
  }
  if (sourceKind?.includes('spring') || sourceKind?.includes('dotnet')) states.push('api-response');
  return unique(states);
}

function inferRoles(text) {
  const roles = [];
  const rolePatterns = [
    /\b(?:roles|allowedRoles|authorities)\s*[:=]\s*\[([^\]]+)\]/gi,
    /has(?:Any)?Role\s*\(([^)]+)\)/gi,
    /@PreAuthorize\s*\(\s*['"`]([^'"`]+)['"`]\s*\)/gi,
    /\b(?:userRole|currentRole|role)\s*:\s*['"`]([A-Za-z0-9_-]+)['"`]/gi
  ];

  for (const pattern of rolePatterns) {
    for (const match of text.matchAll(pattern)) {
      roles.push(...Array.from(match[1].matchAll(/['"`]?([A-Za-z][A-Za-z0-9_-]*)['"`]?/g)).map((role) => role[1]));
    }
  }

  return unique(roles)
    .filter((role) => !['role', 'roles', 'hasRole', 'hasAnyRole'].includes(role))
    .map((role) => role.toLowerCase());
}

function mergeRoute(routes, route) {
  const existing = routes.get(route.path);
  if (!existing) {
    routes.set(route.path, route);
    return;
  }

  routes.set(route.path, {
    ...existing,
    component: existing.component === 'UnknownPage' ? route.component : existing.component,
    roles: unique([...existing.roles, ...route.roles]),
    actions: unique([...existing.actions, ...route.actions]),
    fields: unique([...existing.fields, ...route.fields]),
    states: unique([...existing.states, ...route.states]),
    testIds: unique([...existing.testIds, ...route.testIds]),
    sourceFiles: unique([...existing.sourceFiles, ...route.sourceFiles]),
    sourceKinds: unique([...existing.sourceKinds, ...route.sourceKinds]),
    apiMethods: unique([...existing.apiMethods, ...route.apiMethods])
  });
}

function inferUsers(routes) {
  const roles = unique(routes.flatMap((route) => route.roles ?? []))
    .filter((role) => role && !['anonymous', 'permitall', 'authenticated', 'user'].includes(role));

  return roles.map((role) => ({
    role,
    username: '',
    password: '',
    access: routes.filter((route) => route.roles.includes(role)).map((route) => route.path),
    note: 'Inferred role only. Add real test credentials/session setup before generating capture workflows.'
  }));
}

function normalizeRoute(value) {
  if (!value || value === '*') return '/';
  const withoutQuery = String(value).split('?')[0].replace(/^\.\//, '');
  if (withoutQuery === '' || withoutQuery === '/') return '/';
  return `/${withoutQuery.replace(/^\/+/, '').replace(/\/+$/, '')}`;
}

function isLikelyApplicationRoute(value) {
  if (!value || value.startsWith('http://') || value.startsWith('https://')) return false;
  return !/\.(?:css|js|mjs|png|jpg|jpeg|gif|svg|ico|webp|woff2?|ttf|map|json)$/i.test(value);
}

function extractArrayProperty(text, property) {
  const pattern = new RegExp(`\\b${property}\\s*:\\s*\\[([^\\]]*)\\]`, 'i');
  const body = text.match(pattern)?.[1];
  if (!body) return [];
  return Array.from(body.matchAll(/['"`]([^'"`]+)['"`]/g)).map((match) => match[1]);
}

function enclosingObject(text, index) {
  const start = findOpeningBrace(text, index);
  if (start < 0) return null;
  const end = findClosingBrace(text, start);
  if (end < 0) return null;
  return text.slice(start, end + 1);
}

function findOpeningBrace(text, index) {
  let inString = false;
  let quote = '';
  let escaped = false;

  for (let cursor = index; cursor >= 0; cursor -= 1) {
    const char = text[cursor];
    if (inString) {
      if (escaped) escaped = false;
      else if (char === '\\') escaped = true;
      else if (char === quote) inString = false;
      continue;
    }

    if (char === '"' || char === "'" || char === '`') {
      inString = true;
      quote = char;
      continue;
    }

    if (char === '{') return cursor;
    if (char === ';' || char === ']') return -1;
  }
  return -1;
}

function findClosingBrace(text, start) {
  let depth = 0;
  let inString = false;
  let quote = '';
  let escaped = false;

  for (let cursor = start; cursor < text.length; cursor += 1) {
    const char = text[cursor];
    if (inString) {
      if (escaped) escaped = false;
      else if (char === '\\') escaped = true;
      else if (char === quote) inString = false;
      continue;
    }

    if (char === '"' || char === "'" || char === '`') {
      inString = true;
      quote = char;
      continue;
    }

    if (char === '{') depth += 1;
    if (char === '}') depth -= 1;
    if (depth === 0) return cursor;
  }

  return -1;
}

function nearbyText(text, index, radius = 1200) {
  return text.slice(Math.max(0, index - Math.floor(radius / 2)), Math.min(text.length, index + radius));
}

function joinRoutes(prefix, suffix) {
  return normalizeRoute([prefix, suffix].filter(Boolean).join('/').replace(/\/+/g, '/'));
}

function stripTags(value) {
  return value.replace(/<[^>]+>/g, ' ').replace(/\{[^}]+\}/g, ' ').replace(/\s+/g, ' ').trim();
}

function firstMatch(text, pattern) {
  return text.match(pattern)?.[1];
}

function toComponentName(value) {
  const name = slug(value).split('-').map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`).join('');
  return name ? `${name}Page` : 'UnknownPage';
}

function unique(values) {
  return Array.from(new Set(values.filter(Boolean).map((value) => String(value).trim()).filter(Boolean)));
}

function uniqueBy(items, keyFn) {
  const seen = new Set();
  return items.filter((item) => {
    const key = keyFn(item);
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}
